#! /usr/bin/env bash

set -e -o pipefail

gcl='git clean -fxd'

if [ $# -eq 0 ]; then
	$gcl
	exit 0
fi

if [ $# -eq 1 ]; then
	cd "$1" && $gcl
	exit 0
fi

s=`basename $0`
echo "usage: $s [dir]"
exit 1
