#!/usr/bin/env bash
# git clean -fxd without confirmation (see gcl).

set -euo pipefail

if [[ $# -gt 1 ]]; then
	printf 'usage: %s [dir]\n' "${0##*/}" >&2
	exit 1
fi

if [[ $# -eq 1 ]]; then
	cd "$1"
fi

git clean -fxd
