#! /usr/bin/env bash

set -e -o pipefail

readonly NARGS="$#"

if  [[ "$NARGS" = "0" ]]; then
	args=
else
	args="--follow ""$@"
fi

git log \
	--graph \
	--pretty=format:'%C(yellow)%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%ar) %C(bold blue)<%an>%Creset' \
	--abbrev-commit \
	--date=short \
	--date-order \
	$args

