#! /usr/bin/env bash

set -e -o pipefail

case "$#" in
	1)
		tag="$1"
		;;
	*)
		s=`basename $0`
		echo "delete remote tag"
		echo "usage: $s tag"
		exit 1
		;;
esac

git push origin :refs/tags/$tag

