#! /usr/bin/env bash

sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
sudo add-apt-repository ppa:duggan/bats --yes

sudo apt-get update
sudo apt-get upgrade


sudo apt-get install lmodern texlive-fonts-recommended texlive-xetex
sudo apt-get install texlive-bibtex-extra biber

sudo apt-get install texstudio
sudo apt-get install inkscape
sudo apt-get install bats
sudo apt-get install vim

sudo apt-get install g++-4.9 gcc-4.9
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 90
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 90

sudo apt-get install zlib1g-dev libbz2-dev libboost-dev

sudo apt-get install git git-svn


