#! /usr/bin/env bash

conda install -y bwa samtools snakemake vcftools bcftools bedtools vcftools picard

conda install -y bioawk

conda install -y blast bwa novoalign last bowtie2 hisat2 minimap tophat mosaic star

conda install -y miniasm daligner

conda install -y freebayes gatk-framework varscan

conda install -y kraken kallisto 

conda install -y jellyfish khmer 
