#! /usr/bin/env bash

#set -e
set -x

envs=(
		"p:prophyle pandas xopen"
		"py38:python=3.8"
		"py39:python=3.9"
		"py310:python=3.10"
	)

for e in "${envs[@]}"; do
    k=${e%%:*}
    v=${e#*:}
	echo "===================="
	echo "$k"
	echo "===================="
	mamba create -c bioconda --name $k -y $v || echo "Environment $k already exists"
	#source activate $k
	#conda install -y $v
	#source deactivate
done
