#! /usr/bin/env bash

set -e
set -o pipefail


#####################
# 1) SET UP VARIABLES
#####################

echo "Setting up variables"
d="$HOME/miniconda"
tmpd="$(mktemp -d)"

conda="$d/bin/conda"
mamba="$d/bin/mamba"

if [[ -f "$conda" && -f "$mamba" ]]; then
	echo "Both conda and mamba already installed, quitting"
	exit 0
fi

if [[ "$(uname)" == "Linux" ]]; then
	url="https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh"
else
	url="https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh"
fi


######################
# 2) INSTALL MINICONDA
######################

if [[ -f "$conda" ]]; then
	echo "Conda already installed ($conda), skipping"
else
	echo "Installing miniconda"
	(cd "$tmpd" && wget -O miniconda.sh "$url")
	/usr/bin/env bash "$tmpd/miniconda.sh" -b -p "$d"
fi


##################
# 3) INSTALL MAMBA
##################

if [[ -f "$mamba" ]]; then
	echo "Mamba already installed ($mamba), skipping"
else
	"$conda" install -y mamba
fi


######################
# 4) UPDATE EVERYTHING
######################

"$mamba" update conda -y
"$mamba" update --all -y

