#! /usr/bin/env bash

set -o verbose
#set -e

# manual installation:
# - Mendeley
# - Chrome
# - Dropbox
# - Rust

# repositories
sudo add-apt-repository ppa:duggan/bats -y
sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
sudo add-apt-repository ppa:ubuntu-elisp/ppa -y
sudo add-apt-repository ppa:nilarimogard/webupd8 -y
sudo add-apt-repository ppa:webupd8team/atom -y
sudo add-apt-repository ppa:george-edison55/cmake-3.x -y
sudo add-apt-repository ppa:webupd8team/java -y
#sudo add-apt-repository ppa:stvs/tomate -y
sudo add-apt-repository "deb http://archive.canonical.com/ precise partner" -y
sudo add-apt-repository "deb http://archive.canonical.com/ubuntu $(lsb_release -sc) partner" -y
sudo add-apt-repository ppa:webupd8team/sublime-text-3 -y
sudo add-apt-repository ppa:ecometrica/servers
sudo apt-get update

# editors
sudo apt-get install -y vim
sudo apt-get install -y vim-gtk
sudo apt-get install -y emacs
sudo apt-get install -y emacs-snapshot
sudo apt-get install -y emacs-snapshot-el
sudo apt-get install -y atom
sudo apt-get install -y eric
sudo apt-get install -y netbeans
sudo apt-get install -y kdevelop

# players
sudo apt-get install -y mplayer
sudo apt-get install -y vlc
sudo apt-get install -y radiotray

# git
sudo apt-get install -y git
sudo apt-get install -y git-svn
curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash

# tex
sudo apt-get install -y lmodern
sudo apt-get install -y texlive-full
sudo apt-get install -y texlive-latex-recommended
sudo apt-get install -y texlive-latex-extra
sudo apt-get install -y texlive-generic-extra
sudo apt-get install -y texlive-fonts-recommended
sudo apt-get install -y texlive-xetex
sudo apt-get install -y texlive-humanities
sudo apt-get install -y texstudio
sudo apt-get install -y latexmk
sudo apt-get install -y texlive-bibtex-extra 
sudo apt-get install -y biber
sudo apt-get install -y xzdec

# graphical editors
sudo apt-get install -y inkscape
sudo apt-get install -y gnuplot
sudo apt-get install -y gimp
sudo apt-get install -y wkhtmltopdf  
sudo apt-get install -y pdftk

# bats
sudo apt-get install -y bats

# makes
sudo apt-get install -y software-properties-common
sudo apt-get install -y cmake
sudo apt-get install -y cmake-data
sudo apt-get install -y autotools-dev
sudo apt-get install -y autoconf

# gcc
sudo apt-get install -y g++-5
sudo apt-get install -y gcc-5
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 90

# libraries
sudo apt-get install -y zlib1g-dev
sudo apt-get install -y libbz2-dev
sudo apt-get install -y libboost-dev
sudo apt-get install -y libboost-all-dev
sudo apt-get install -y libqt4-core
sudo apt-get install -y qt4-dev-tools
sudo apt-get install -y libncurses5-dev
sudo apt-get install -y libcurl4-openssl-dev
sudo apt-get install -y libcairo2-dev
sudo apt-get install -y libjpeg8-dev

# other langs
sudo apt-get install -y octave
sudo apt-get install -y golang
sudo apt-get install -y oracle-java8-installer
sudo apt-get install -y clang


# bioinformatics
sudo apt-get install -y igv

# tools
sudo apt-get install -y tmux
sudo apt-get install -y htop
sudo apt-get install -y iotop
#sudo apt-get install -y tomate
sudo apt-get install -y openssh-server
sudo apt-get install -y sshfs
sudo apt-get install -y parallel

# non-oss
sudo apt-get install -y acroread
sudo apt-get install -y skype
sudo apt-get install -y grive
sudo apt-get install -y sublime-text-installer

#misc
sudo apt-get install -y libgnome2-bin

# python
sudo apt-get install -y python-pip
sudo apt-get install -y python-dev
sudo apt-get install -y python-nose
sudo apt-get install -y python-jinja2
sudo apt-get install -y cython
sudo apt-get install -y python3-setuptools
sudo apt-get install -y python3-dev
sudo apt-get install -y cython3
sudo easy_install3 pip
sudo pip3 install --upgrade pip
sudo pip3 install --upgrade virtualenv
sudo pip3 install --upgrade snakemake
sudo pip3 install --upgrade biopython
sudo pip3 install --upgrade numpy
sudo pip3 install --upgrade pysam
sudo pip3 install --upgrade cython

# linux brew
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/linuxbrew/go/install)" || true
