#! /usr/bin/env bash

set -o verbose

# repository for scientifical software
brew tap homebrew/science

# git
brew install git
brew install git-lfs
brew install git-extras
brew install git-review
brew install git-svn-abandon
brew install git-fixup
brew install git-open
brew install hub

# development tools
brew install pv
brew install emacs
#brew install vim
brew install gdb
#brew install valgrind
#brew install Caskroom/cask/netbeans-cpp
brew install gperftools
#brew install homebrew/x11/gv
brew install clang-format
brew install autoconf
brew install automake
brew install rust
brew install ccat

# misc tools
brew install gnu-time
brew install coreutils
brew install exiftool
brew install recoverjpeg

# bash completion
brew install bash-completion
brew tap homebrew/completions

# libraries
brew install boost
brew install libstxxl
brew install tclap
brew install open-mpi

#node.js
brew install ruby
brew install npm

# other unix utilities
if [[ `uname` == 'Linux' ]]; then
#	brew install bash
	echo ""
else
	brew install gcc
fi
brew install htop
#brew install iotop
brew install links
brew install mc

# tools for pdf
brew install pdfgrep
brew install svg2pdf

# graphical editors
brew cask install xquartz
brew cask install dia
brew cask install inkscape
brew cask install gimp
brew cask install libreoffice
brew install Caskroom/cask/wkhtmltopdf
brew install imagemagick

# latexdiff
brew install homebrew/tex/latexdiff
brew install homebrew/tex/git-latexdiff


# docker
#brew install docker
#brew install docker-machine
#brew install docker-compose

# pypy
brew install readline --without-ncurses
brew install pypy
brew install pypy3

# pdf library for gnuplot
brew install pdflib-lite

# several useful Linux tools
brew install unrar
brew install graphviz
brew install gnuplot
brew install wget
#brew install socat
brew install rename
brew install ascii
brew install parallel
brew install http://git.io/sshpass.rb

# video
brew install ffmpeg

# tools for bioinformatics formats
brew install picard-tools
brew install samtools
brew install sambamba
brew install bamtools
brew install bcftools
brew install vcftools
brew install bioawk
brew install fastq-tools

# tools for genome assembly
brew install blast
#brew install celera-assembler
brew install gatb
#brew install kissplice

# tools for read simulation
brew install dwgsim
brew install flux-simulator

# tools for read mapping
brew install mrfast
brew install novoalign
brew install bowtie2
brew install bwa
brew install snap-aligner
brew install gmap-gsnap
brew install last

# read counters
brew install jellyfish kmc
brew install kraken

# other bioinformatics tools
brew install kallisto
brew install seqan
brew install igv
brew install igvtools

# tools for manipulation with newick trees
brew install newick-utils
brew install newicktools

brew install armadillo
brew install mobile-shell

brew install rename
