#! /usr/bin/env bash

set -o verbose

readonly PROGNAME=$(basename $0)
readonly PROGDIR=$(dirname $0)
readonly -a ARGS=("$@")
readonly NARGS="$#"

######################
# SETUP ENV
######################
if [[ ! -f ~/miniconda/bin/mamba ]]; then
	$PROGDIR/_install_miniconda_base
	conda install -y mamba
fi
x="mamba install -y"


######################
# WORKFLOW MANAGERS
######################
$x snakemake


######################
# PROGRAMMING & PLOTTING
######################
$x pandas xopen numpy ete3
$x jupyterlab bash_kernel
#$x pyqt
$x markdown
$x pandas
$x pylint
$x yapf
$x biopython
$x pysam


######################
# K-MER COUNTING
######################
$x jellyfish
$x khmer


######################
# DATA DOWNLOADERS
######################
$x sra-tools
#$x entrez-direct


######################
# BIODATA MANIPULATION
######################
$x bcftools sambamba samtools seqtk bioawk


######################
# ALIGNMENT
######################
$x blast
$x bwa
$x bowtie2
$x minimap2
$x edlib


######################
# VARIANT CALLING
######################
$x ococo
$x freebayes
#$x gatk-framework
$x varscan


######################
# ASSEMBLY
######################
$x miniasm
$x mccortex
#$x abyss
#$x amos
#$x daligner
#$x dazz_db
#$x fermi
#$x megahit


######################
# METAGENOMICS
######################
$x prophyle prophasm prophex
$x kraken2
#$x gb_taxonomy_tools
#$x kraken-all
#$x kallisto
#$x centrifuge


######################
# READ SIMULATION
######################
$x rnftools
$x nanosim-h
#$x art
#$x flux-simulator
#$x simlord

