#! /usr/bin/env bash

set -e -o pipefail

d=`mktemp -d`
minid=$HOME/miniconda

if [[ -d $minid ]]; then
	echo "Miniconda directory already exists ($minid)"
	exit 0
fi

if [[ `uname` == 'Linux' ]]; then
	url=https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
else
	url=https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
fi

cd $d
curl $url > miniconda.sh
bash miniconda.sh -b -p $minid

export PATH=$PATH:$minid/bin

conda update conda -y
conda update --all -y

conda install -y conda-build

