#! /usr/bin/env bash

#set -e
#set -x

envs=(
		"p:prophyle pandas xopen ete3"
		"rnftools:rnftools"
		"nanosimh:nanosim-h"
		"jf:jellyfish>=2"
		"py:python=3.10 xopen numpy pandas pprint"
		"py311:python=3.11"
		"py312:python=3.12"
	)

for e in "${envs[@]}"; do
    k=${e%%:*}
    v=${e#*:}
	echo "===================="
	echo "$k"
	echo "===================="
	mamba create -c bioconda --name $k -y $v || echo "Environment $k already exists"
	#source activate $k
	#conda install -y $v
	#source deactivate
done
