#! /usr/bin/env bash

set -x

git_update_repos && echo "Git update finished"
conda update -y conda && conda update --all -y && echo "Conda update finished"
brew update && brew upgrade && echo "Brew update finished"
npm update -g && echo "NPM update finished"
(gem update `gem list | cut -d ' ' -f 1`) && echo "GEM update finished"
tldr --update && echo "TL;DR update finished"

echo "All updates finished"

