#! /usr/bin/env bash
# Shortcut to gzcat | less

set -o

prog=`basename $0`

if [ $# -ne 2 ]; then
	echo "compress pdf using ghost script"
	echo "usage: $prog in.pdf out.pdf"
	exit 1
fi

/usr/bin/env gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/printer -dNOPAUSE -dQUIET -dBATCH -sOutputFile=$2 $1

