#! /usr/bin/env bash

if [ $# -ne 1 ]; then
	echo "use one parameter for the new file"
	exit 1
fi

echo "#! /usr/bin/env bash" > $1
echo "" >> $1
echo "" >> $1
echo "#if [ $# -ne 1 ]; then" >> $1
echo "#	echo \"use one parameter for the new file\"" >> $1
echo "#	exit 1" >> $1
echo "#fi" >> $1
echo "" >> $1

chmod +x $1