#! /usr/bin/env bash

BASEDIR=$(dirname "$0")

set -x

if [ $# -eq 0 ]; then
	cp "$BASEDIR/samples/sample.mk" Makefile
	exit 0
fi

if [ $# -eq 1 ]; then
	cp "$BASEDIR/samples/sample.mk" "$1"
	exit 0
fi


echo "use at most parameter for the new file or no parameter for Makefile"
exit 1
