#! /usr/bin/env bash

BASEDIR=$(dirname "$0")
SAMPLE="$BASEDIR/samples/sample.snakefile"

if [ $# -eq 0 ]; then
	cp $SAMPLE Snakefile
	exit 0
fi

if [ $# -eq 1 ]; then
	cp $SAMPLE "$1"
	exit 0
fi

echo "use at most parameter for the new file or no parameter for Makefile"
exit 1
