#! /usr/bin/env bash

if [ $# -ne 1 ]; then
	echo "use one parameter for the new file"
	exit 1
fi

echo ".PHONY: all clean" > $1
echo "" >> $1
echo "all:" >> $1
echo "	" >> $1
echo "" >> $1
echo "clean:" >> $1
echo "	" >> $1
echo "" >> $1
