#! /usr/bin/env bash

#set -e -o pipefail

# prerequisities:
# - links: brew install links


if [ $# -ne 1 ]; then
	s=`basename $0`
	echo "usage: $s param"
	exit 1
fi

#perl -pe 's/\*\*/\n\*/g' | \

tmp=`mktemp`

#perl -pe 's/[0-9]+\./\n/g' | \
links -dump "http://ssjc.ujc.cas.cz/search.php?heslo=$1&where=full_text&hsubstr=no" | \
	perl -pe 's/\*//g' | \
	grep -v '\[ [A-Za-z]* *\] ' | \
	perl -pe 's/†//g' | \
	grep -v "^\s*$" | \
	grep -v "©" \
	> $tmp

egrep '^\s*(Nalezeno |Upozornění)' $tmp > /dev/null 2> /dev/null
if [ $? -eq 0 ]; then
	cat $tmp | \
	egrep -v '^ *(Nalezeno|Upozornění)' | \
	grep -v '^\s*statí.\s*$' | \
	perl -pe 's/^   /\* /g' | \
	perl -pe 's/^\*\s{4,50}/\t/g' | \
	egrep --color=auto "$1|$"
else
	cat $tmp | \
	sed '1s/^\s*/\* /' | \
	perl -pe 's/^\s+/\t/g' | \
	egrep --color=auto "$1|$"
fi

