#! /usr/bin/env bash

set -u
set -f
set -e
set -o pipefail

readonly PROGNAME=$(basename $0)
readonly PROGDIR=$(dirname $0)
readonly -a ARGS=("$@")
readonly NARGS="$#"

usage() {
	cat <<- EOF
	usage: $PROGNAME options
	EOF
}

main() {
	if [ $NARGS -ne 1 ]; then
		usage
		exit 1
	fi
	find "${ARGS[0]}" -name '*.fastq' -exec cat "{}" \; | seqtk seq -a -
}

main
