#! /usr/bin/env bash

# requires coreutils for realpath

if [ $# -ne 3 ]; then
	s=`basename $0`
	echo "usage: $s file.fa k histogram.txt"
	exit 1
fi

fasta=`realpath $1`
k=$2
hist=`realpath $3`

tmpdir=`mktemp -d`

cores=`sysctl -n hw.ncpu`
chars=`ls -l $fasta | awk '{ print $5 }'`

cd $tmpdir

jellyfish count -m $k -t $cores -s $chars -C $fasta
jellyfish histo mer_counts.jf > $hist
