#! /usr/bin/env bash


fff(){
    find "$1" -type f | grep -v "\.git/" | grep -v "\.snakemake"
}


if [[ $# -eq 0 ]]; then
    fff .
    exit 0
fi

if [[ $# -eq 1 ]]; then
    fff $1
    exit 0
fi

s=`basename $0`
echo "usage: $s [directory]"
exit 1

