#! /usr/bin/env python3

import argparse
import os
import sys
import stat

langs = ["cz", "en", "fr", "de"]

langs_codes = {
	"cz": "cs",
	"en": "en",
	"fr": "fr",
	"de": "de",
}

template="""#! /usr/bin/env bash

set -e -o pipefail


if [ $# -eq 0 ]; then
	s=`basename $0`
	echo "usage: $s phrase"
	exit 1
fi

q=`echo "$*" | sed 's/ /\+/g'`

open "https://translate.google.com/#{fr}/{to}/$q"
"""

for fr in langs:
	for to in langs:
		if fr==to:
			continue
		fn="g{}{}".format(fr,to)
		with open(fn,"w") as f:
			f.write(template.format(fr=langs_codes[fr],to=langs_codes[to]))
		st = os.stat(fn)
		os.chmod(fn, st.st_mode | stat.S_IEXEC)

