#! /usr/bin/env bash

#set -x
set -o pipefail

if [ $# -ne 1 ] && [ $# -ne 0 ]; then
	echo "illegal number of parameters"
	exit 1
fi

(
if [ $# -eq 0 ]; then
	cd ~/github
	echo "#! /usr/bin/env bash"
else
	cd "$1"
fi

for d in `ls -d */ 2>/dev/null || echo ""`; 
do
	(
	if [ -L $d ]; then
		true
	else
		cd "$d"
		p=`pwd`

		p_up=$(cd .. && echo `pwd`)
		p_home=$(cd ~ && echo `pwd`)

		if [ -d ".git" ]; then
			p_rel=`realpath --relative-to=${p_home} $p`
 			repo=`git remote -v | grep fetch | grep origin | awk '{print $2;}'`
 			echo "mkdir -p $p_rel && git clone --recursive $repo $p_rel"
		else
			#echo "not a git repo; going to iterate though its subdirs"
			$0 ./
		fi
	fi
	)
done;
)
