#! /usr/bin/env bash

#set -x
set -o pipefail

if [ $# -ne 1 ] && [ $# -ne 0 ]; then
	echo "illegal number of parameters"
	exit 1
fi

(
if [ $# -eq 0 ]; then
	cd ~/github
else
	cd "$1"
fi

for d in `ls -d */`; 
do
	(
	if [ -L $d ]; then
		1
	else
		cd "$d"

		p=`pwd`

		if [ -d ".git" ]; then
			echo
			hrr
			echo "Directory  $p"
			hrr

			git pull --rebase || git pull
		else
			#echo "not a git repo; going to iterate though its subdirs"
			$0 ./
		fi
	fi
	)
done;
)
