#! /usr/bin/env bash

#set -x
set -o pipefail

if [ $# -ne 1 ]; then
	echo "illegal number of parameters"
	exit 1
fi

(
cd "$1"
for d in `ls -d */`; 
do
	(
	echo
	hrr	
	echo 
	echo "Directory  $d"
	echo 

	cd "$d"
	if [ -d ".git" ]; then
		git pull --rebase || git pull
	else
		echo "not a git repo; going to iterate though its subdirs"
		$0 ./
	fi
	)
done;
)
