#! /usr/bin/env bash

set -e -o pipefail


if [ $# -ne 0 ]; then
	s=`basename $0`
	echo "open web of the current git repository"
	echo "usage: $s"
	exit 1
fi

url=`git remote -v | grep fetch | awk '{print $2}'`
http=`echo $url | sed 's/^git/http/g' | sed 's/ssh:\/\/[a-z]*\@/http:\/\//g' | sed 's/^http/https/g'`
branch=`git branch | grep "*" | awk '{print $2}'`

#echo "Repo URL:       $url"
#echo "HTTP address:   $http"
#echo "Current branch: $branch"

# todo: add directory
# todo: add support for bitbucket

if [[ "$branch" == "master" ]]; then
	open="$http"
else
	open="$http/tree/$branch"
fi

#echo "URL:            $open"

open "$open"

