#! /usr/bin/env bash

# print first and last line of a file

set -e
set -o pipefail
set -u
#set -f

readonly PROGNAME=$(basename $0)
readonly PROGDIR=$(dirname $0)
readonly -a ARGS=("$@")
readonly NARGS="$#"

if [[ $NARGS -ne 1 ]]; then
	echo "usage: $PROGNAME options"
	exit 1
fi

head -n1 "$1"
tail -n1 "$1"

