#! /usr/bin/env python3
# Encoding: UTF-8
"""Print a horizontal line across the screen"""

import fcntl
import termios
import struct
import sys


def terminal_size():
    data = fcntl.ioctl(0, termios.TIOCGWINSZ, struct.pack('HHHH', 0, 0, 0, 0))
    h, w, hp, wp = struct.unpack('HHHH', data)
    return w, h


number = 1
if len(sys.argv) > 1:
    number = int(sys.argv[1])

for _ in range(number):
    print('–' * terminal_size()[0])
