#! /usr/bin/env bash

export http_proxy="www-cache:3128"
export https_proxy="www-cache:3128"
export ftp_proxy="www-cache:8021"

#exec socat STDIO PROXY:www-cache:$1:$2,proxyport=3128

git config --global core.gitproxy ~/bin/__proxy_curie_git

