#! /usr/bin/env bash

#set -e -o pipefail

# prerequisities:
# - links: brew install links


where=hesla

function usage {
	s=`basename $0`
	echo "Find definition of a Czech word in SSJČ (Slovník spisovného jazyka českého)"
	echo "usage: $s [-v] word"
	echo "	-v verbose (find all occurrences)"
	exit $1
}

while getopts "hv" o; do
case "$o" in
    h)
	usage
	;;
    v)
	where=full_text
	;;

    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
esac
done


posargs=$(( $# - $OPTIND + 1 ))

if [[ posargs -ne 1 ]]; then
	usage 1
fi

w=${@:$OPTIND:1}


#perl -pe 's/\*\*/\n\*/g' | \

tmp=`mktemp`

#perl -pe 's/[0-9]+\./\n/g' | \
links -dump "http://ssjc.ujc.cas.cz/search.php?heslo=$w&where=$where&hsubstr=no" | \
	perl -pe 's/\*//g' | \
	grep -v '\[ [A-Za-z]* *\] ' | \
	perl -pe 's/†//g' | \
	grep -v "^\s*$" | \
	grep -v "©" \
	> $tmp

egrep '^\s*(Nalezeno |Upozornění)' $tmp > /dev/null 2> /dev/null
if [ $? -eq 0 ]; then
	cat $tmp | \
	egrep -v '^ *(Nalezeno|Upozornění)' | \
	grep -v '^\s*statí.\s*$' | \
	perl -pe 's/^   /\* /g' | \
	perl -pe 's/^\*\s{4,50}/\t/g' | \
	egrep --color=auto "$w|$"
else
	cat $tmp | \
	sed '1s/^\s*/\* /' | \
	perl -pe 's/^\s+/\t/g' | \
	egrep --color=auto "$w|$"
fi

