#! /usr/bin/env python3

import sys
import os
import argparse
import math

substitutions = {

	"fibonacci" : {
			"0": "01",
			"1": "0",
			},

	"tribonacci" : {
			"0": "01",
			"1": "02",
			"2": "0",
			},

	"thuemorse" : {
			"0": "01",
			"1": "10",
			},

}

def apply_subst(subst,word):
	return "".join([subst[x] for x in word])

parser = argparse.ArgumentParser()
#parser.add_argument(
#		"experiment",
#		type=str,
#		help="display a square of a given number"
#	)
parser.add_argument(
		"-s","--substitution",
		choices=substitutions.keys(),
		dest="s",
		default="tribonacci",
	)
parser.add_argument(
		"-i","--iterations",
		dest="i",
		type=int,
		default=10,
	)
parser.add_argument(
		"-a","--init-letter",
		dest="a",
		default="0",
	)
parser.add_argument(
		"-w","--line-width",
		dest="w",
		type=int,
		default="60",
	)

args = parser.parse_args()

word = args.a
subst = substitutions[args.s]

for _ in range(args.i):
	word = apply_subst(subst, word)

for i in range(int(math.ceil(len(word)/args.w))):
	print (word[i*args.w:(i+1)*args.w])


