#! /usr/bin/env python3
"""Convert TSVs to XLSX
"""

import argparse
import csv
import os

from xlsxwriter.workbook import Workbook


def load_table(tsv):
    with open(tsv, 'r') as f:
        table = []
        tsv_reader = csv.reader(f, delimiter='\t')
        table = list(tsv_reader)
        #for row in enumerate(tsv_reader):
        #    table.append(row)
    return table


def tsv_to_xlsx(tsvs, xlsx):
    workbook = Workbook(xlsx)

    for tsv in tsvs:
        name = os.path.basename(tsv)
        xlsx_compatible_name = name[:31]
        worksheet = workbook.add_worksheet(xlsx_compatible_name)
        with open(tsv, 'r') as f:
            table = load_table(tsv)
            for i, row in enumerate(table):
                if i != 0:
                    row[1:] = list(map(str, row[1:]))
                worksheet.write_row(i, 0, row)

    workbook.close()


def main():
    parser = argparse.ArgumentParser(description="")

    parser.add_argument(
        'tsv',
        type=str,
        nargs='+',
        metavar='data.tsv',
    )

    parser.add_argument(
        'xlsx',
        type=str,
        metavar='output.xlsx',
    )

    args = parser.parse_args()

    tsv_to_xlsx(args.tsv, args.xlsx)


if __name__ == "__main__":
    main()
