#! /usr/bin/env python3

import argparse
import os
import sys

from Bio import SeqIO

def distance(seq1, seq2):
	s1=seq1.upper()
	s2=seq2.upper()
	return sum ([s1[i] != s2[i] for i in range(len(s1))])


def distance_matrix(fasta_fn):
	record_dict = SeqIO.to_dict(SeqIO.parse(fasta_fn, "fasta"))
	keys=list(record_dict)
	c=len(keys)
	for i in range(c-1):
		k1=keys[i]
		k2=keys[i+1]
		l1=len(record_dict[k1])
		l2=len(record_dict[k2])
		assert l1==l2, "{} ({}) != {} ({})".format(l1, k1, l2, k2)

	for i in range(c):
		seq1=record_dict[keys[i]]
		print(keys[i], end="")
		for j in range(c):
			seq2=record_dict[keys[j]]
			print("\t{}".format(distance(seq1, seq2)), end="")
			sys.stdout.flush()
		print()


def main():

	parser = argparse.ArgumentParser(description="")

	parser.add_argument('fasta_fn',
			metavar='<aligned.fa>',
		)

	args = parser.parse_args()

	distance_matrix(args.fasta_fn)

if __name__ == "__main__":
  main()
