#! /usr/bin/env bash

# FASTQ-one-line format -> FASTQ

set -u
set -f
set -e
set -o pipefail

readonly PROGNAME=$(basename $0)
readonly PROGDIR=$(dirname $0)
readonly -a ARGS=("$@")
readonly NARGS="$#"

if [[ $NARGS == 0 ]]; then
	perl -pe 's/\t/\n/g'
	exit 0
fi

if [[ $NARGS == 1 ]]; then
	cat "${ARGS[0]}" | perl -pe 's/\t/\n/g'
	grep '^>'
	exit 0
fi

echo "usage: $PROGNAME [seqs.fq]"
exit 1
