#! /usr/bin/env python3

"""Convert TSVs to XLSX
"""

import argparse
import csv
from xlsxwriter.workbook import Workbook

def tsv_to_xlsx(tsvs, xlsx):
    workbook = Workbook(xlsx)
    for tsv in tsvs:
        worksheet = workbook.add_worksheet(tsv[:31])
        with open(tsv, 'r') as f:
            tsv_reader = csv.reader(f, delimiter='\t')
            for row, data in enumerate(tsv_reader):
                if row!=0:
                    data[1:]=list(map(float,data[1:]))
                worksheet.write_row(row, 0, data)

    workbook.close()


def main():
    parser = argparse.ArgumentParser(description="")

    parser.add_argument('tsv',
            type=str,
            nargs='+',
            metavar='data.tsv',
        )

    parser.add_argument('xlsx',
            type=str,
            metavar='<assignments.bam>',
        )

    args = parser.parse_args()

    tsv_to_xlsx(args.tsv, args.xlsx)

if __name__ == "__main__":
    main()
